### ISSUE TITLE
modify maintenance plan -- can't add images?

### ISSUE THREAD

**Issue by jingweiwu** [automationWisdri/WisdriIS#3]
在维保过程中，不管是技术主管，还是维保人员都不能添加图片。参与人员好像也添加不了。这个问题还需要进一步测试确认。

**Comment by allenright** [comment]
修改维保方案时不能修改图片
至于有没有这个需求，看实际使用的情况吧

**Comment by allenright** [comment]
已增加修改方案时提交图片功能，提交后，新方案会附上老方案已有图片
